# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: XMU AutoSignIn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 15 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get chromedriver
      run: |
        wget http://npm.taobao.org/mirrors/chromedriver/87.0.4280.88/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/bin/
    - name: SignIn
      run: |
        python AutoSignIn.py
      env:
        STUID: ${{ secrets.STUID }}
        PW: ${{ secrets.PW }}
        SERVER: ${{ secrets.SERVER }}
        SCKEY: ${{ secrets.SCKEY }}
        MAIL_NOTICE: ${{ secrets.MAI_NOTICE }}
        MAILBOX: ${{ secrets.MAILBOX }}
